return {
  -- 'rcarriga/nvim-notify',
  -- config = function()
  --   require('notify').setup {
  --     stages = 'fade',
  --     timeout = 300,
  --     background_colour = '#15191f',
  --     icons = {
  --       ERROR = ' ',
  --       WARN = ' ',
  --       INFO = ' ',
  --       DEBUG = ' ',
  --       TRACE = '✎ ',
  --     },
  --     max_width = 40,
  --     minimum_width = 40,
  --     render = 'wrapped-compact',
  --     -- top_down = false,
  --   }
  -- end,
}
