return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  opts = {
    preset = 'helix',
    keys = {
      scroll_down = '<c-a>',
      scroll_up = '<c-e>',
    },
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },
    spec = {
      { '<leader>q', group = '[Q]uit', mode = { 'n' } },
      { '<leader>c', group = '[C]ode', mode = { 'n', 'x' } },
      { '<leader>d', group = '[D]ebug' },
      { '<leader>r', group = '[R]ename' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>w', group = '[W]orkspace' },
      { '<leader>t', group = '[T]oggle' },
      { '<leader>gh', group = '[G]it [H]unk', mode = { 'n', 'v' } },
      { '<leader>m', group = '[M]ove', mode = { 'n', 'v' } },
      { '<leader>t', group = '[T]abs', mode = { 'n', 'v' } },
      { '<leader>g', group = '[G]it', mode = { 'n' } },
      { '<leader>h', group = '[H]elp', mode = { 'n' } },
      { '<leader>m', group = '[M]arks', mode = { 'n' } },
      { '<leader>x', group = '[X] Snippets', mode = { 'n', 'v' } },
      { '<leader>o', group = '[O]bsidian', mode = { 'n' } },
      { '<leader>p', group = '[P]ickers', mode = { 'n' } },
    },
  },
}
